feat(library): Add support for Caddy
unikraft/catalog pull request #12
Opened 2023-11-14 22:26 UTC by razvand

Introduce Caddy bincompat run. Build Caddy as static PIE using a Dockerfile, inspired by Caddy's own Docker setup. Use `xcaddy` to build. The build uses binary compatibility mode (i.e. the `base` image).

Add:

* `Kraftfile`: build / run rules, including pulling the `base` image
* `Dockerfile`: base filesystem, with binary and libraries
* `README.md`: document how to use
* `Caddyfile`: Caddy configuration file

2023-11-14 22:31 UTC, nderjung commented on library/caddy/2.7/Dockerfile
> +	apt-get -yqq install libcap2-bin
```Dockerfile
RUN set -xe; 
    apt-get update; \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      git \
      libcap2-bin \
    ;
```

2023-11-14 22:31 UTC, nderjung commented on library/caddy/2.7/Dockerfile
> +env XCADDY_GO_BUILD_FLAGS "-buildmode=pie -ldflags '-linkmode external -extldflags -static-pie'"
Uppercase `ENV`

2023-11-14 22:31 UTC, nderjung commented on library/caddy/2.7/Kraftfile
> +runtime: index.unikraft.io/official/base:latest
```yaml
runtime: unikraft.org/base:latest
```

2023-11-14 22:32 UTC, nderjung commented on library/caddy/2.7/README.md
> +kraft run unikraft.org/caddy:2.7 -p 2015:2025
`-p 2015:2015`

2023-11-15 15:41 UTC, nderjung commented on library/caddy/2.7/Dockerfile
> +	apt-get -yqq install libcap2-bin
Please use this exactly, also with indentation

2023-12-26 20:31 UTC, StefanJum requested changes
The README needs to be updated with the build and run commands like the other prs. Everything else works.

2023-12-27 12:18 UTC, StefanJum reviewed
One small comment, all good besides that.

2023-12-27 12:18 UTC, StefanJum commented on library/caddy/2.7/README.md
> +This directory contains the definition for the `unikraft.org/caddy:2.7` image running Nginx.
```suggestion
This directory contains the definition for the `unikraft.org/caddy:2.7` image.
```

2024-02-12 18:24 UTC, StefanJum reviewed
I get this error when running
```
en1: Interface is up
[    0.103447] ERR:  [libdevfs] Failed to create /dev: 20
[    0.106231] ERR:  [libukboot] Init function at 0x11bfa0 returned error -1
```

2024-02-21 18:47 UTC, nderjung approved these changes
All good!

2024-02-21 18:48 UTC, merged