feat(examples): Add core-utils
unikraft/catalog pull request #141
Opened 2024-11-23 13:19 UTC by feohuman

Add basic linux utils (ls, cat, pwd, uniq) in unikernel format, running on debian:bookworm.

2024-11-26 14:57 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2024-12-07 07:17 UTC, razvand requested changes
Apply updates to all `Dockerfile`s as in the feedback (i.e. use `runtime:main`).

Squash the two commits in a single one.

Rename directory to `coreutils/` instead of `core-utils`.

See my other comments.

2024-12-07 07:17 UTC, razvand commented on examples/core-utils/Dockerfile
> +COPY --from=build /usr/bin/ls /usr/bin/ls
```suggestion
# Binaries
COPY --from=build /usr/bin/ls /usr/bin/ls 
```

2024-12-07 07:17 UTC, razvand commented on examples/core-utils/Dockerfile
> +# Dependencies
```suggestion

# Library dependencies
```

2024-12-07 07:17 UTC, razvand commented on examples/core-utils/Kraftfile.cat
> +    source: https://github.com/unikraft/lib-libelf.git
```suggestion
runtime: base:latest
```

2024-12-07 07:17 UTC, razvand commented on examples/core-utils/README.md
> +```bash
```suggestion
```console
```

2024-12-07 07:17 UTC, razvand commented on examples/core-utils/README.md
> +# Linux Core Utils
```suggestion
# Linux Coreutils
```

2024-12-07 07:17 UTC, razvand commented on examples/core-utils/README.md
> +Where `cmd` is the command you want to execute.
```suggestion

Where `cmd` is the command you want to execute.
```

2024-12-13 19:35 UTC, razvand requested changes
Apply updates to all `Dockerfile`s as in the feedback (i.e. use `runtime: base:latest`).

Squash all commits into a single commit.

Rename directory to `coreutils/` instead of `core-utils/`.

2024-12-13 19:35 UTC, razvand commented on examples/core-utils/README.md
> +This directory contains a minimal Debian instance featuring ore utils such as ls, cat, pwd, etc., running on Unikraft.
```suggestion
This directory contains a minimal Debian instance featuring core utilities such as `ls`, `cat`, `pwd`, etc., running on Unikraft.
```

2024-12-13 19:35 UTC, razvand commented on examples/core-utils/Kraftfile.ls
> +    version: staging
```suggestion
runtime: base:latest
```

2024-12-13 19:35 UTC, razvand commented on examples/core-utils/Kraftfile.pwd
> +- qemu/x86_64
```suggestion
runtime: base:latest
```

2024-12-13 19:35 UTC, razvand commented on examples/core-utils/Kraftfile.uniq
> +- qemu/x86_64
```suggestion
runtime: base:latest
```

2024-12-13 19:35 UTC, razvand commented on examples/core-utils/Kraftfile.cat
> +- qemu/x86_64
```suggestion
```

2024-12-13 19:35 UTC, razvand commented on examples/core-utils/.gitignore
> +*.txt
What is the point of this?

2024-12-14 16:17 UTC, razvand requested changes
See my comments.

Update your commit such that the signed-off name is similar to the one in the signature, i.e.:

```
Signed-off-by: George-Theodor Paraschiva <paraschiva.george.theodor@gmail.com>
```

Update the commit message to detail the tools / utils that you added in the catalog.

2024-12-14 16:17 UTC, razvand commented on examples/coreutils/Kraftfile.ls
> +- qemu/x86_64
```suggestion
```

2024-12-14 16:17 UTC, razvand commented on examples/coreutils/Kraftfile.cat
> +cmd: ["/usr/bin/cat"]
Update the command to list the contents of a file. Add some files to the local directory in the repository than copy them to the `Dockerfile`:

```Dockerfile
COPY myfs/ .
```

2024-12-14 16:17 UTC, razvand commented on examples/coreutils/Kraftfile.uniq
> +cmd: ["/usr/bin/uniq"]
Also pass an argument to it from the local filesystem, e.g. `cmd: ["/usr/bin/uniq", "/file.txt"]`

2024-12-14 16:17 UTC, razvand commented on examples/coreutils/README.md
> +kraft run --rm --plat qemu --arch x86_64 -K Kraftfile.{`cmd`} .
```suggestion
kraft run --rm --plat qemu --arch x86_64 -K Kraftfile.<cmd> .
```

2024-12-14 16:17 UTC, razvand commented on examples/coreutils/README.md
> +Where `cmd` is the command you want to execute.
```suggestion
Where `<cmd>` is the command you want to execute.
```

2024-12-14 18:00 UTC, razvand requested changes
Just some small comments and then we can merge.

2024-12-14 18:08 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-12-14 18:08 UTC, merged