feat(examples): Add HTTP server using tokio, built natively
unikraft/catalog pull request #54
Opened 2024-01-28 23:24 UTC by Mihnea27

Introduce a HTTP tokio server, that can be built natively for Unikraft.

2024-03-10 19:37 UTC, razvand requested changes
See my comments. The `README.md` needs update to make it similar to the one in PR #97 and in other `http-...` examples.

Please move this example from the `examples/` directory to the `native/` directory.

Is `Cargo.lock` really required? Since it's generated by `cargo`?

2024-03-10 19:37 UTC, razvand commented on examples/http-tokio/Kraftfile
> +specification: v0.7
```suggestion
spec: v0.6

```

2024-03-10 19:37 UTC, razvand commented on examples/http-tokio/Kraftfile
> +name: http-tokio
```suggestion
name: http-rs-tokio
```

2024-03-10 19:37 UTC, razvand commented on examples/http-tokio/README.md
> +# Simple HTTP Server using 'tokio'
Update the `README.md` file to feature similar contents to the `README.md` file from PR #97 .

2024-03-10 19:37 UTC, razvand commented on examples/http-tokio/README.md
> +# Simple HTTP Server using 'tokio'
See also the `README.md` contents from other `http-...` examples.

2024-03-10 19:37 UTC, razvand commented on examples/http-tokio/README.md
> +```
Don't document using a bridge, it's complicated. Instead use `kraft run -p`.

2024-03-10 19:37 UTC, razvand commented on examples/http-tokio/README.md
> +sudo kraft run -W --memory 2G --network bridge:virbr0 -a netdev.ip=172.44.0.2/24:172.44.0.1
```suggestion
kraft run --rm -M 2G -p 8080:8080 --plat qemu --arch x86_64 .
```

2024-03-10 19:49 UTC, razvand requested changes

2024-03-10 19:49 UTC, razvand commented on examples/http-tokio/Cargo.toml
> +name = "http-tokio"
```suggestion
name = "http-rs-tokio"
```

2024-03-10 19:49 UTC, razvand commented on examples/http-tokio/Kraftfile
> +  version: 0.16.1
```suggestion
  version: stable
```

2024-03-10 19:49 UTC, razvand commented on examples/http-tokio/README.md
> +curl 172.44.0.2:8080
This will become `curl localhost:8080` after the change above for `kraft run`.

2024-03-10 19:49 UTC, razvand commented on examples/http-tokio/src/main.rs
> +                let contents = "<h1>Hello, world!</h1>";
```suggestion
                let contents = "Hello, World!\r\n";
```

2024-03-10 19:49 UTC, razvand commented on examples/http-tokio/Kraftfile
> +  musl: staging
```suggestion
  musl: stable
```

2024-03-10 19:49 UTC, razvand commented on examples/http-tokio/Kraftfile
> +    version: staging
```suggestion
    version: stable
```

2024-03-10 19:55 UTC, razvand requested changes
Squash all commits into a single one.

2024-03-10 19:55 UTC, razvand requested changes
See the linter warnings / errors. They are shown automatically at the bottom of the PR conversation.

2024-03-10 20:27 UTC, razvand requested changes
Add a `.gitignore` file to ignore `/Cargo.lock` and `/target/`.

2024-03-13 21:16 UTC, mkroening requested changes
This is a very manual way of building an HTTP server with tokio. Even much more manual than with tiny-http (https://github.com/unikraft/catalog/pull/20).

For showcasing basic TCP connections, this might be fine, but for HTTP I'd suggest to use [hyper](https://github.com/hyperium/hyper) (the de-facto standard HTTP crate for Rust).

See https://hyper.rs/guides/1/server/hello-world/ for an example.

What would also be interesting is showcasing a server framework like [axum](https://github.com/tokio-rs/axum) (also part of the tokio project).

I can open PRs for `http-rs-hyper` (framework-less example) and `http-rs-axum` (framework example) in the coming days.

What do you guys think?

2024-03-13 21:16 UTC, mkroening commented on examples/http-tokio/Cargo.toml
> +tokio = {version = "1",  features = ["full"] }
```suggestion
tokio = { version = "1",  features = ["full"] }
```

2024-03-14 08:27 UTC, mkroening commented
I opened https://github.com/unikraft/catalog/pull/100.

2024-03-19 20:34 UTC, Mihnea27 commented
Sorry for my late reply @mkroening, I was away the past days. Yes, i agree it is a very barebones implementation for a HTTP server, my point was to prove that `tokio` works, as initially I had some problems with it. Depending on what @razvand considers, I can close this PR and leave the one with `axum` that you opened. There is already an example with `tokio` in bincompat mode in the catalog anyways.

2024-08-22 10:02 UTC, razvand commented
@Mihnea27 , @mkroening , we will close this PR, since PR #100 (Axum) is now in.

2024-08-22 10:02 UTC, closed without merging